name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Clear npm cache and remove node_modules
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -rf .next

      - name: Install dependencies
        run: |
          npm install
          npm install sharp @next/swc-linux-x64-gnu @next/swc-linux-x64-musl

      - name: Patch SWC
        run: npm run dev & sleep 5 && kill $!

      - name: Build
        run: |
          npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
